# Generated by Django 4.2.3 on 2023-07-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(help_text='insert the title of snacks', max_length=255),
        ),
    ]
