# Generated by Django 4.2.3 on 2023-07-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_alter_snack_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
